=== RAFVG-import/OSM-ItalyFuelStations/schema.json
{
  "$id": "http://example.com/example.json",
  "type": "object",
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "id": {
      "$id": "/properties/id",
      "type": "integer",
      "title": "The Id Schema ",
      "default": 0,
      "examples": [
        17720
      ]
    },
    "lat": {
      "$id": "/properties/lat",
      "type": "number",
      "title": "The Lat Schema ",
      "default": 0,
      "examples": [
        37.31492614746094
      ]
    },
    "lon": {
      "$id": "/properties/lon",
      "type": "number",
      "title": "The Lon Schema ",
      "default": 0,
      "examples": [
        13.571385383605957
      ]
    },
    "tags": {
      "$id": "/properties/tags",
      "type": "object",
      "properties": {
        "operator": {
          "$id": "/properties/tags/properties/operator",
          "type": "string",
          "title": "The Operator Schema ",
          "default": "",
          "examples": [
            "A.Nuara E Figli Srl"
          ]
        },
        "brand": {
          "$id": "/properties/tags/properties/brand",
          "type": "string",
          "title": "The Brand Schema ",
          "default": "",
          "examples": [
            "Pompe Bianche"
          ]
        },
        "source:date": {
          "$id": "/properties/tags/properties/source:date",
          "type": "string",
          "title": "The Source:date Schema ",
          "default": "",
          "examples": [
            "2018-04-11"
          ]
        }
      }
    }
  }
}

=== RAFVG-import/OSM-ItalyFuelStations/tmp/3record.json
[
    {
        "id": 26366,
        "lat": 45.953020113006275,
        "lon": 13.43632087111473,
        "tags": {
            "brand": "Tamoil",
            "description": "Statale 56 Di Gorizia  Km. 21  Dir. Ovest 34071",
            "addr:postcode": "34071",
            "addr:city": "Cormons",
            "source:date": "2018-04-09"
        }
    },
    {
        "id": 11611,
        "lat": 45.95676739726052,
        "lon": 13.466316964626344,
        "tags": {
            "operator": "Servizi & Gestioni Italia S.R.L.",
            "brand": "Q8",
            "description": "V.Le V.Giulia Ss 356 Km 45+511 S/N 34071",
            "addr:postcode": "34071",
            "addr:city": "Cormons",
            "source:date": "2018-04-09"
        }
    },
    {
        "id": 21433,
        "lat": 45.95026200465828,
        "lon": 13.475195467472076,
        "tags": {
            "operator": "Zorgniotti & Piu Di Zorgniotti Oscar & C. S.A.S.",
            "brand": "Api-Ip",
            "description": "Statale 56 Di Gorizia  Km. 24  Dir. Gorizia 34071",
            "addr:postcode": "34071",
            "addr:city": "Cormons",
            "source:date": "2018-04-09"
        }
}
]
